pull_request_rules:
  - name: Rebase pull requests once when it's labeled with `rebase`
    conditions:
      - label=rebase
    actions:
      rebase: {}
      label:
        remove:
          - rebase

  - name: Automatic merge when CI passes
    conditions:
      - check-success=package nvim [x86_64-linux]
    actions:
      merge:
        method: rebase
      delete_head_branch:

  - name: Warn on conflicts
    conditions:
      - conflict
    actions:
      comment:
        message: |
          This pull request is now in conflicts. Could you fix it @{{author}}? 🙏
      label:
        toggle:
          - conflict

  - name: Toggle labels based on CI state
    conditions:
      - check-failure=Run Flake Checker
    actions:
      label:
        toggle:
          - "CI:fail"

  - name: Add "WIP" label when the title contains "WIP"
    conditions:
      - title~=WIP
    actions:
      label:
        toggle:
          - WIP
