# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  blink-cmp = {
    pname = "blink-cmp";
    version = "40380e711b616a28affb0f4086a2f7de2f2a556b";
    src = fetchgit {
      url = "https://github.com/saghen/blink.cmp";
      rev = "40380e711b616a28affb0f4086a2f7de2f2a556b";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-0+KyxOh7WUm6rRLfb936X48qBhYL5aRYn2OBEj4G1/s=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./blink-cmp-40380e711b616a28affb0f4086a2f7de2f2a556b/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-11-05";
  };
  blink-pairs = {
    pname = "blink-pairs";
    version = "8e935d07ab6a3843565afd6a6d56456678cbf43f";
    src = fetchgit {
      url = "https://github.com/saghen/blink.pairs";
      rev = "8e935d07ab6a3843565afd6a6d56456678cbf43f";
      fetchSubmodules = false;
      deepClone = false;
      leaveDotGit = false;
      sparseCheckout = [ ];
      sha256 = "sha256-L1sG5vW8W1z5TMf6IRrkmNqNiCvPePT0eA+dR8yBZMI=";
    };
    cargoLock."Cargo.lock" = {
      lockFile = ./blink-pairs-8e935d07ab6a3843565afd6a6d56456678cbf43f/Cargo.lock;
      outputHashes = {
        
      };
    };
    date = "2025-11-07";
  };
}
